<?php

return array (
  'windows nt 6.0'	 => 'Windows Longhorn',
  'windows nt 5.2'	 => 'Windows 2003',
  'windows nt 5.0'	 => 'Windows 2000',
  'windows nt 5.1'	 => 'Windows XP',
  'windows nt 4.0'	 => 'Windows NT 4.0',
  'winnt4.0'			   => 'Windows NT 4.0',
  'winnt 4.0'			=> 'Windows NT',
  'winnt'				=> 'Windows NT',
  'windows 98'		=> 'Windows 98',
  'win98'				=> 'Windows 98',
  'windows 95'		=> 'Windows 95',
  'win95'				=> 'Windows 95',
  'windows'			=> 'Unknown Windows OS',
  'os x'				=> 'Mac OS X',
  'ppc mac'			=> 'Power PC Mac',
  'freebsd'			=> 'FreeBSD',
  'ppc'				=> 'Macintosh',
  'linux'				=> 'Linux',
  'debian'			=> 'Debian',
  'sunos'				=> 'Sun Solaris',
  'beos'				=> 'BeOS',
  'apachebench'		=> 'ApacheBench',
  'aix'				=> 'AIX',
  'irix'				=> 'Irix',
  'osf'				=> 'DEC OSF',
  'hp-ux'				=> 'HP-UX',
  'netbsd'			=> 'NetBSD',
  'bsdi'				=> 'BSDi',
  'openbsd'			=> 'OpenBSD',
  'gnu'				=> 'GNU/Linux',
  'unix'				=> 'Unknown Unix OS'
);
