#!/usr/bin/env php
<?php
// boot.php should always set up the include paths to point to the copy of Madeam 
// in the application/vendor directory
require 'application/vendor/madeam/src/madeam.php';
new madeam\console\Create($_SERVER['argv']);